-- MySQL Script generated by MySQL Workbench
-- Sat Aug 18 13:08:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrators` (
  `idAdministrator` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministrator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculty` (
  `idFaculty` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `EnrolleesLimit` INT NULL,
  `Administrator_id` INT NULL,
  `Enrollee_id` VARCHAR(45) NULL,
  PRIMARY KEY (`idFaculty`),
  CONSTRAINT `fk_Faculty_Administrators1`
    FOREIGN KEY (`Administrator_id`)
    REFERENCES `mydb`.`Administrators` (`idAdministrator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Faculty_Administrators1_idx` ON `mydb`.`Faculty` (`Administrator_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificate` (
  `idCertificate` INT NOT NULL AUTO_INCREMENT,
  `SchoolSubjectsId` VARCHAR(45) NULL,
  `SubjectScore` DECIMAL NULL,
  `AverageScore` DECIMAL NULL,
  PRIMARY KEY (`idCertificate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enrollees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enrollees` (
  `idEnrollee` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Faculty_id` INT NOT NULL,
  `Certificate_id` INT NOT NULL,
  PRIMARY KEY (`idEnrollee`, `Faculty_id`, `Certificate_id`),
  CONSTRAINT `fk_Enrollees_Faculty`
    FOREIGN KEY (`Faculty_id`)
    REFERENCES `mydb`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollees_Certificate1`
    FOREIGN KEY (`Certificate_id`)
    REFERENCES `mydb`.`Certificate` (`idCertificate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Enrollees_Faculty_idx` ON `mydb`.`Enrollees` (`Faculty_id` ASC) VISIBLE;

CREATE INDEX `fk_Enrollees_Certificate1_idx` ON `mydb`.`Enrollees` (`Certificate_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`SchoolSubjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SchoolSubjects` (
  `idSchoolSubjects` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Certificate_idCertificate` INT NOT NULL,
  PRIMARY KEY (`idSchoolSubjects`),
  CONSTRAINT `fk_SchoolSubjects_Certificate1`
    FOREIGN KEY (`Certificate_idCertificate`)
    REFERENCES `mydb`.`Certificate` (`idCertificate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_SchoolSubjects_Certificate1_idx` ON `mydb`.`SchoolSubjects` (`Certificate_idCertificate` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
